# Generated by Django 5.0 on 2026-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'ingrédient")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantité en stock')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('L', 'Litre'), ('ml', 'Millilitre'), ('unit', 'Unité')], default='kg', max_length=10, verbose_name='Unité de mesure')),
                ('minimum_stock_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Niveau de stock minimum')),
                ('last_restocked', models.DateTimeField(blank=True, null=True, verbose_name='Dernier réapprovisionnement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
        ),
    ]
